### PR TITLE
Build on JDK11 by default

### PR DESCRIPTION
**Pull request by karllessard**
As discussed and voted by SIG JVM, the minimal supported JDK version for distributed artifacts has moved from Java8 to Java11. Java17 build is also supported by the activation of the `jdk17` Maven profile.

### CODE REVIEW

**Comment by Craigacp** [comment]
Should we add a module-info.java at the same time? I think it would be pretty short, just adding a dependency on `jdk.unsupported` for Unsafe.

**Comment by karllessard** [comment]
@Craigacp , so I've checked at the different options on how to support unit testing in a classic Maven project setup and none are very appealing, so I suggest that we continue to simply disable the module path in the surefire plugin config like I currently do, and let it use the regular classpath instead.

**Review by Craigacp — APPROVED** [review]
LGTM

**Comment by Craigacp** [comment]
> @Craigacp , so I've checked at the different options on how to support unit testing with Java modules in a classic Maven project setup and none are very appealing, so I suggest that we continue to simply disable the module path in the surefire plugin config like I currently do, and let unit tests use the regular classpath instead.

Sure. Module testing is a pain and if it's going to cause a lot of problems we can leave it till later.

**Pull request merged**
